### PR TITLE
WINUI-3359 -Changed the API names in WinUI UG contend.

### PR DESCRIPTION
**Pull request by NanthiniMahalingam**
**Description**

Updated the WinUI APIs based on WinUI APIs breaking changes task https://syncfusion.atlassian.net/browse/WINUI-3312

### CODE REVIEW

**Comment by MuneeshKumarG** [comment]
rebuild

**Comment by NanthiniMahalingam** [comment]
rebuild

**Comment by kannans24** [comment]
rebuild

**Comment by MuneeshKumarG** [comment]
rebuild

**Review by MuneeshKumarG — APPROVED** [review]
This is fine

**Pull request merged**
