### PR TITLE
WINUI-2776 : Include API reference links for WinUI Gauges UG changes

### PR DESCRIPTION
**Pull request by VishalOmprasad**
### Description ###
To add API reference links for WinUI Gauges' properties in UG content.

### CODE REVIEW

**Review by vigneshrameshsync — APPROVED** [review]
The changes are fine.

**Comment by vigneshrameshsync** [comment]
rebuild

**Comment by VishalOmprasad** [comment]
rebuild

**Comment by vigneshrameshsync** [comment]
rebuild

**Pull request merged**
