### PR TITLE
WinUI-3091 : Added the API properties link in the rating and busyindicator control.

### PR DESCRIPTION
**Pull request by Priyanka-Vijayasankar**
### Description:
Added the API Properties link in rating and busy indicator control.

### CODE REVIEW

**Comment by Priyanka-Vijayasankar** [comment]
rebuild

**Comment by Priyanka-Vijayasankar** [comment]
rebuild.

**Comment by Priyanka-Vijayasankar** [comment]
rebuild

**Review by Manivannan-E — APPROVED** [review]
Changes are fine.

**Pull request merged**
