### PR TITLE
WINUI-3116 - Defining source data type documentation references x:Type code removed 

### PR DESCRIPTION
**Pull request by vijayarasan**
https://www.syncfusion.com/feedback/37967/winui-datagrid-defining-source-data-type-documentation-references-xtype- Defining source data type documentation references x:Type code removed

### CODE REVIEW

**Comment by vijayarasan** [comment]
rebuild

**Comment by susmitha-sundar** [comment]
rebuild

**Comment by susmitha-sundar** [comment]
rebuild

**Comment by kannans24** [comment]
rebuild

**Review by susmitha-sundar — APPROVED** [review]

**Pull request merged**
